spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_simulator
    username: demo
    password: test1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

simulation:
  acceleratedMinutesPerSecond: 60
  schedulerIntervalMillis: 2000
  progressIncrementPerTick: 0.02
  defaultRoute:
    origin: MDE
    destination: BOG
  phases:
    boardingMinutes: 20
    taxiOutMinutes: 15
    takeoffClimbMinutes: 10
    cruiseMinutes: 90
    descentMinutes: 15
    landingMinutes: 10
    taxiInMinutes: 10